### ISSUE TITLE
Automating Kubernetes Deployments with Azure DevOps and Docker

### ISSUE THREAD

**Issue by nehadjsh** [nehadjsh/RentCarManagement#3]
# Automating Kubernetes Deployments with Azure DevOps and Docker

---

### 1:  Sign in to Azure Portal

 1. Go to: https://portal.azure.com/
2. Open the "Container Registries" Service 
- In the top search bar, type "Container Registries"
- Select it from the search results.
- Or follow the images

![Image](https://github.com/user-attachments/assets/96260134-c295-4add-b73c-6265ed08261d)

![Image](https://github.com/user-attachments/assets/f521f29d-ff21-4594-bb33-d3c46a6cabd0)

### 3. Create a container registry
- Click the + Create button to start the registry creation process.

![Image](https://github.com/user-attachments/assets/d5668384-934d-4d5f-b7e3-2ff74a0b2eca)

### 4.  Fill in Registry Details
Fill in the form with the following:

- Subscription: Select your Azure subscription
- Resource Group: Select existing or create a new one: ACR
- Registry name: rentcar
- Location: Choose your preferred region: East US
- SKU: Standard

![Image](https://github.com/user-attachments/assets/fa0639fe-82f5-41c2-9254-a16198982578)

### 5. Review and Create
- Click Review + Create
- After validation, click Create

![Image](https://github.com/user-attachments/assets/679d1d62-144a-4a42-97a3-98a6b3c5befd)

### 6. Go to Resource

- Once deployment is complete, click Go to the resource

![Image](https://github.com/user-attachments/assets/45ccec14-ee15-4af8-a2d0-0dc916bfa3b7)
![Image](https://github.com/user-attachments/assets/c4ba07ba-3192-4694-9388-81abffa5f2a5)

### 7. (Optional) Enable Admin Access
- On the registry page, click Access keys from the left menu
- Toggle Admin user to Enabled
- Copy Username and Password if needed for Docker login

![Image](https://github.com/user-attachments/assets/77f005f3-8842-47ee-b352-77324cf9cb64)

---

### 1. Open your Azure DevOps project
- Go to https://dev.azure.com/ and open your project.

### 2. Go to Project Settings
- From the bottom-left corner, click Project settings.

![Image](https://github.com/user-attachments/assets/08341adc-d347-4d6c-b437-4c00b2807da2)

### 3. Select "Service Connections
- Then click on + New service connection.

![Image](https://github.com/user-attachments/assets/d0f7a231-8e79-4051-94e8-78c59e10f6e2)

### 4. Choose a service connection or connection type
-  Choose Docker Registry 
- Click Next.

![Image](https://github.com/user-attachments/assets/900f11a9-0c9b-4b85-a759-78fba55d81ce)

### 5. Fill in the new Docker Registry connection

- Choose Azure connection registry 
- Select  Authentication type
- Choose the Azure subscription
- Select  Azure container registry: rentcar
- Give the connection a name: rentACRConnection
- Check Grant access permission to all pipelines
- Click Save

![Image](https://github.com/user-attachments/assets/639c9b08-cd45-4194-9ab5-9cd842eaf965)

---

## ☸️ Create Azure Kubernetes Service (AKS) via Azure Portal

 Step-by-Step Guide

### 1. Log in to Azure Portal
- Go to https://portal.azure.com/ and sign in.

### 2. Search for "Kubernetes Services"
- Use the search bar at the top and click on the result.
 
![Image](https://github.com/user-attachments/assets/0bff3092-0e8c-4ded-a70f-b97fb5d651c9)

### 3. Click "+ Create" 
- Click + Create > Kubernetes cluster

![Image](https://github.com/user-attachments/assets/36d5b154-995a-4ec4-85e4-dee36e47fcfe)

### 4. Fill Cluster DetailsIn:

- Subscription: Select your Azure subscription
- Resource group: AKS
- Cluster name: rentcarAKS
- Region: East US
- Kubernetes version: Use the latest or default
- Availability zones: Zones 1
- Click Next.

![Image](https://github.com/user-attachments/assets/580b8814-e5c8-4c26-9414-594f518fe8b4)

### 5. Configure Node Pool (optional)
You can adjust the default node settings or leave them as they are

![Image](https://github.com/user-attachments/assets/57f4d7ce-c9a9-4ad3-b5a4-71affc8ed19b)

![Image](https://github.com/user-attachments/assets/ac05a3c1-5a75-427d-ba68-ec9813d91012)

![Image](https://github.com/user-attachments/assets/b1fb05e6-50d3-413c-90f1-d26d38c6a7d0)

### 6. Integrations
- Connect your cluster to an Azure Container Registry 
- Click Next.

![Image](https://github.com/user-attachments/assets/a9c08603-b683-48cf-921f-8b824fc3a0df)

### 7. Review and CreateClick 
- Review + Create, then click Create once validation passes.

![Image](https://github.com/user-attachments/assets/80c004dd-42f4-4803-8067-d2bf7dbe0613)

### 8. Go to the Resource
- Once the cluster is deployed, click Go to resource

![Image](https://github.com/user-attachments/assets/ff3681a7-f08e-4019-8838-86377d0ecc65)

![Image](https://github.com/user-attachments/assets/b67a5748-f07d-40b8-845f-4dd79aff7109)

---

## 🚀 CI/CD Pipeline: Build, Push Docker Image, and Deploy to Kubernetes
Step-by-Step Guide

###  1. Open Azure DevOps and Create New Pipeline

1. Go to [Azure DevOps](https://dev.azure.com).
2. Select your project.
3. From the left sidebar, go to **Pipelines**.
4. Click on **New Pipeline**.

![Image](https://github.com/user-attachments/assets/8fbb1218-f95d-452c-bc98-4f5f933ba33a)

![Image](https://github.com/user-attachments/assets/078b5b37-1383-488a-b634-be21ec723dec)

###  2. Connect to GitHub Repository

1. Choose **GitHub** as the source.
2. Authorize access if prompted.
3. Select the repository containing your project.

![Image](https://github.com/user-attachments/assets/73a7aa7e-9ec4-495b-bd06-dec266fee662)

![Image](https://github.com/user-attachments/assets/cf32d43e-b2c4-4c90-a841-6c1337e99ff6)

![Image](https://github.com/user-attachments/assets/ec77fa5f-3e24-410d-8e6a-60334cbdbb37)

![Image](https://github.com/user-attachments/assets/dac586c8-6d23-40e7-8859-7d5f187304f1)

![Image](https://github.com/user-attachments/assets/16b950d9-6206-4230-8dcb-dca682f5ed35)

###  3. Use Starter pipeline
1. Choose **"Use Starter pipelinee"**.
2. Click **Continue**.

![Image](https://github.com/user-attachments/assets/b96912c0-70d5-4e3c-bd9f-414e04250806)

---

###  4. Review your pipeline YAML 

 1. Define Variables

- Variables are used to store reusable values like image name, registry name, namespace, etc.

```variables:
  imageName: 'rentcar' # Docker image name
  containerRegistry: 'rentcar.azurecr.io' # ACR name
  kubernetesNamespace: 'default' # Kubernetes namespace
  deploymentName: 'rentcar-deployment'
  dockerRegistryServiceConnection: 'rentACRConnection'

```

![Image](https://github.com/user-attachments/assets/ace0003e-0224-4b65-a58a-3b49a750756e)

2. Build and Push Docker Image
 This step has two main tasks: building the Docker image and pushing it to Azure Container Registry (ACR).
- Search in the right-side menu for: Docker
- Select: Docker

![Image](https://github.com/user-attachments/assets/be68561c-3c62-43e5-ace6-92ae9459be7d)

 Fill in the details:
- Container registry: rentACRConnection
- Container repository: rentcar.azurecr.io/rentcar
- Choose Command: buildAndPush
- Choose Dockerfile
- Click on **Add**.

![Image](https://github.com/user-attachments/assets/e17fdb54-7e2b-4d1c-91ba-927f880f7354)

![Image](https://github.com/user-attachments/assets/1f3a707b-7eb0-47ee-b673-8c1f3a4c14a9)

Purpose:

Uses the Docker task to build an image from the Dockerfile
Tags the image with the build ID for versioning
Pushes the built Docker image to your ACR
Makes it available for use in Kubernetes deployments

3. Kubernetes Deployment
This task applies the Kubernetes manifest file to deploy the application to AKS:
- Search in the right-side menu for: Kubectl
- Select: Kubectl

![Image](https://github.com/user-attachments/assets/13666cce-3baf-47f5-a29c-d9aa1385d5dd)

 Fill in the details:
- Choose Service connection type: Azure Resource Manager
- Select Azure subscription
- Select Resource group: AKS
- Kubernetes cluster:rentcarAKS
- Namespace: default
- Choose Command: apply
- Inline configuration:

```Inline configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rent-app-deployment
  labels:
    app: rent-app
spec:
  replicas: 1  # Number of pods
  selector:
    matchLabels:
      app: rent-app
  template:
    metadata:
      labels:
        app: rent-app
    spec:
      containers:
      - name: rentcar 
        image: rentcar.azurecr.io/rentcar:latest  # Docker Hub image
        ports:
        - containerPort: 8081  # Port inside the container
---
apiVersion: v1
kind: Service
metadata:
  name: rent-app-service
spec:
  selector:
    app: rent-app
  ports:
  - protocol: TCP
    port: 80        # External port exposed by the service
    targetPort: 8081  # Port the container listens on
  type: LoadBalancer # Exposes the service with an external IP (use NodePort for Minikube or local clusters)


```

- Click on **Add**.

![Image](https://github.com/user-attachments/assets/4d3319a8-5338-431a-a3ba-503061da4bed)

![Image](https://github.com/user-attachments/assets/3492d9fc-93cf-429e-84e8-e0fb047f614a)

![Image](https://github.com/user-attachments/assets/443024e0-4be0-4b56-997e-112ce7a720b6)

Note:
 This is the complete YAML:

```yaml
trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'rentcar' # Docker image name
  containerRegistry: 'rentcar.azurecr.io' # ACR name
  kubernetesNamespace: 'default' # Kubernetes namespace
  deploymentName: 'rentcar-deployment'
  dockerRegistryServiceConnection: 'rentACRConnection'

steps:

- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    command: buildAndPush
    repository: 'rentcar.azurecr.io/rentcar'
    dockerfile: '**/dockerfile'
    containerRegistry: 'rentACRConnection'
    tags: 'latest'



- task: Kubernetes@1
  displayName: 'Deploy to AKS'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Azure subscription'
    azureResourceGroup: 'AKS'
    kubernetesCluster: 'rentcarAKS'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configurationType: 'inline'
    inline: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: rent-app-deployment
        labels:
          app: rent-app
      spec:
        replicas: 3  # Number of pods
        selector:
          matchLabels:
            app: rent-app
        template:
          metadata:
            labels:
              app: rent-app
          spec:
            containers:
            - name: rentcar 
              image: rentcar.azurecr.io/rentcar:latest  # Docker Hub image
              ports:
              - containerPort: 8081  # Port inside the container
      ---
      apiVersion: v1
      kind: Service
      metadata:
        name: rent-app-service
      spec:
        selector:
          app: rent-app
        ports:
        - protocol: TCP
          port: 80        # External port exposed by the service
          targetPort: 8081  # Port the container listens on
        type: LoadBalancer # Exposes the service with an external IP (use NodePort for Minikube or local clusters)
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'

```

---

### 5. Save and Run the Pipeline

1. Click **Save and Run**.
2. The pipeline will start automatically.
3. Make sure the service connection is authorized when prompted.

![Image](https://github.com/user-attachments/assets/43106b95-ea04-4dd3-a388-25b9ad2a68af)

![Image](https://github.com/user-attachments/assets/8f64df3e-f64d-4d3c-973c-2052fad03cf4)

![Image](https://github.com/user-attachments/assets/5bd20200-4db5-4f13-8dad-1dc02bed893f)

![Image](https://github.com/user-attachments/assets/8af46f1b-800d-41b9-bb3a-84e99a7cdb87)

- Follow the steps to approve the permissions

![Image](https://github.com/user-attachments/assets/f74b7eb9-3113-44a9-8308-9be46cc69408)

![Image](https://github.com/user-attachments/assets/0bd213ba-d2e0-4dc7-9eb8-14b6dc07e0b1)

![Image](https://github.com/user-attachments/assets/60ed4c22-9594-499b-826f-fe5e619789ed)

![Image](https://github.com/user-attachments/assets/175b323d-10d6-475c-a180-d119b0a2270a)

Operations completed

![Image](https://github.com/user-attachments/assets/91971a10-d46d-4a25-a233-666fdb1a8510)

The Docker image is now ready

![Image](https://github.com/user-attachments/assets/d17012bc-f7ed-40b5-a32e-bae166934adf)

---
### Connect Azure Kubernetes (AKS) with Azure CLI

1. Go to **Azure Kubernetes Service** in your portal  
2. Choose the **"Connect"** option  
3. Copy and past the CLI command displayed, 

![Image](https://github.com/user-attachments/assets/0ab029c3-c1fa-45f8-9462-2e2aaeda4e5e)

![Image](https://github.com/user-attachments/assets/c2d7f670-03cb-4d18-84c1-c3c51c54fdcf)

---
### 🔐 Granting AKS Access to Pull Images from Azure Container Registry
These commands are used to allow the AKS (Azure Kubernetes Service) cluster to pull Docker images from the Azure Container Registry (ACR) by assigning the required role to the AKS managed identity.

1. Get the AKS kubelet identity client ID
```
az aks show \
  --resource-group AKS \
  --name rentcarAKS \
  --query "identityProfile.kubeletidentity.clientId" \
  -o tsv
```
What it does:
Retrieves the client ID of the kubelet managed identity used by the AKS cluster. This identity needs permission to access the ACR.

2. Assign the 'AcrPull' role to the AKS identity
```
az role assignment create \
  --assignee <KUBELET_ID> \
  --role AcrPull \
  --scope /subscriptions/<subscriptions-id>/resourceGroups/AKS/providers/Microsoft.ContainerRegistry/registries/rentcar
```
What it does:
Assigns the AcrPull role to the previously retrieved client ID. This allows the AKS cluster to pull container images from the specified ACR.

---
## 🧰 Useful kubectl Commands for Managing AKS

Below is a list of common `kubectl` commands used to monitor, inspect, and manage your Kubernetes resources. These commands help you interact with your AKS (Azure Kubernetes Service) environment from the command line.

---

### 🔍 View and Inspect Resources

- `kubectl get pods`  
  ➤ Lists all running pods in the current namespace.

- `kubectl get po -o wide`  
  ➤ Shows detailed information about each pod, including IPs and nodes.

![Image](https://github.com/user-attachments/assets/11f17a37-7b9b-44d8-88e2-23e5df1ecec0)

- `kubectl get svc`  
  ➤ Lists all services (e.g., ClusterIP, LoadBalancer) in the current namespace.

![Image](https://github.com/user-attachments/assets/28a88453-311b-418f-9185-5a8b35717139)
- Take the external IP address
- Verify the deployed webapp

![Image](https://github.com/user-attachments/assets/ade0dba4-e9b6-45a3-97fe-114d22730bc3)

- `kubectl describe pod <pod-name>`  
  ➤ Displays detailed information about a specific pod, including events and status.

![Image](https://github.com/user-attachments/assets/cbbb39a9-fb05-4b94-b048-131054a66596)

- `kubectl describe deployment <deployment-name>`  
  ➤ Shows deployment configuration, replicas, strategy, and events.

![Image](https://github.com/user-attachments/assets/9559dcd4-a950-473c-b4e5-cc96db99b310)

- `kubectl get pods --watch`  
  ➤ Continuously watches the pod status updates in real-time.

![Image](https://github.com/user-attachments/assets/6979d8ec-39a9-449e-8151-577bd0345d2b)

---

### 🚀 Apply and Manage Resources

- `kubectl apply -f k8s-deployment.yaml`  
  ➤ Applies the configuration defined in your Kubernetes deployment YAML file.
- To control the number of replicas as desired, for example, 4, execute the command:

 1. Change the number of replicas and save the file.

 2. Apply the changes.

 3. Verify.

As we can see, the replicas have been applied.

![Image](https://github.com/user-attachments/assets/d8afd7a8-8a76-46bd-be18-6ffad7323e86)
---
- Let's make a modification to the code and verify the automation.

![Image](https://github.com/user-attachments/assets/d5656dd6-1e62-45b5-8538-c7c587df006d)

![Image](https://github.com/user-attachments/assets/394cca4a-7874-4862-a933-3bd5cd75211d)

-  Pushing the code to GitHub and verifying it.

![Image](https://github.com/user-attachments/assets/74aeaaf0-01df-455b-b701-4f2fa0c04187)

![Image](https://github.com/user-attachments/assets/ee217d83-d6a8-4c2e-b42c-8e4239aded70)

![Image](https://github.com/user-attachments/assets/28906845-9ca1-4d7b-97a8-436c8dedcf1d)

- Now, the automation process is visible as the change is detected and the pipeline runs automatically.

![Image](https://github.com/user-attachments/assets/b69f70b2-c6f8-4686-9e74-e9e64b4ae786)

![Image](https://github.com/user-attachments/assets/8d852b48-9253-4576-b588-fbfa24150425)

- As we can see, the version is now ready for use.

![Image](https://github.com/user-attachments/assets/b2ece249-4950-47ed-a6cb-4108fefcc911)

- Let's verify. Let's take the new external IP.

![Image](https://github.com/user-attachments/assets/ef86d09c-08c1-457f-bc1f-671ef8c1a7c9)

- The new version is now available and running in the cloud.

![Image](https://github.com/user-attachments/assets/6ebe287f-e840-4b5c-a32f-45edc4661298)

---

- `kubectl edit pod <pod-name>`  
  ➤ Opens the pod manifest in an editor so you can modify live configuration (not recommended for production).

![Image](https://github.com/user-attachments/assets/bc0bedf6-d491-4944-8e5f-16acee11e666)

---

### 📡 Events and Live Monitoring

- `kubectl top pod <pod-name>`  
  ➤ Displays resource usage (CPU/Memory) for the specified pod (requires Metrics Server).

![Image](https://github.com/user-attachments/assets/b46e9432-221e-4b4d-92ed-14698c04ec6e)

- `kubectl logs <pod-name>`  
  ➤ Fetches logs from a container inside the pod. Useful for debugging.

![Image](https://github.com/user-attachments/assets/bc497457-f7d4-4062-8865-b325e47ee5a6)

- `kubectl get events`  
  ➤ Shows events in the current namespace, useful for troubleshooting errors and changes.

![Image](https://github.com/user-attachments/assets/8a60454e-30d2-498e-8b84-5f2103eca98f)

- `while true; do kubectl get pods <pod-name>; sleep 2; done`  
  ➤ Continuously checks the status of a specific pod every 2 seconds. Useful during rollout.

![Image](https://github.com/user-attachments/assets/ea7816f0-5d7c-467b-b03a-ee383746bd41)

 - `kubectl get pods<pod-name> -w`
 ➤This command monitors the status of a specific pod in real-time.

![Image](https://github.com/user-attachments/assets/86b0a36a-279e-4162-a528-c980ac4d06c6)

---

### 🗑️ Delete Resources

- `kubectl delete -f k8s-deployment.yaml`  
  ➤ Deletes the Kubernetes resources defined in the given YAML file.

![Image](https://github.com/user-attachments/assets/6904a64c-9ac2-4e7b-ae62-b01ae1eab85b)

---

🟢 Don't forget to delete the resources from Azure.

However, that's not all. It has been really fun!
Don't forget to delete the resources once you're done.

![Image](https://github.com/user-attachments/assets/022a214b-d1a8-4159-9a50-6c7ee3a82958)
